// Builds components/demos/index.ts from the demo files, so the gallery needs no hand-kept list.
import { readdirSync, writeFileSync } from "node:fs"

const dir = new URL("../components/demos/", import.meta.url)
const names = readdirSync(dir)
  .filter(file => file.endsWith(".tsx"))
  .map(file => file.slice(0, -4))
  .sort()

const body = `// Generated by scripts/gen-demos.mjs. Do not edit.
import { lazy, type ComponentType } from "react"

export const demos: Record<string, ComponentType> = {
${names.map(name => `  ${JSON.stringify(name)}: lazy(() => import("./${name}")),`).join("\n")}
}
`
writeFileSync(new URL("index.ts", dir), body)
console.log(`demos: ${names.length}`)
